이동민 PR
biforest/java-baseball pull request #1
Opened 2021-02-19 01:27 UTC by pkalsh

자기 레포에서 자기 브랜치 파고,
여기 자기 브랜치에 이렇게 PR 날리는 거 맞나요?

2021-02-21 13:53 UTC, kouz95 requested changes
첫번째 미션 제출이군요 👏👏👏

코드에서 정성이 많이 느껴져서 저도 열심히 리뷰 드렸습니다 🙂
궁금한게 있으시면 코멘트로 남겨주세요~

화이팅입니다 👍

2021-02-21 13:53 UTC, kouz95 commented on src/main/java/baseball/Application.java
> +        try (Scanner scanner = new Scanner(System.in)) {
`try-with-resources` 사용 하셨네요. 👍

scanner.close()는 자동으로 호출되기 때문에 '무조건 닫아줘야 한다' 라고 생각하지는 않습니다.
[참고 링크](https://www.delftstack.com/ko/howto/java/java-how-to-close-scanner/)

2021-02-21 13:53 UTC, kouz95 commented on src/main/java/baseball/Application.java
> +        } catch (NullPointerException e) {
지금 코드에서 NPE는 개발자의 실수로 발생하는 것 같은데요 (작성하신 파라미터에 대한 null처리)
지금처럼 Exception을 catch하여 콘솔에 그 메세지를 찍어주는것으로 끝나게 된다면, 어디서 실수를 했는지 파악하기 힘들수도 있을것 같다는 생각이 들어요.
그냥 NPE가 터지게 냅두면 stacktrace가 찍히니, 오히려 디버깅 하기 수월할것 같습니다.
try-catch를 지워도 괜찮을 것 같아요.

2021-02-21 13:53 UTC, kouz95 commented on src/main/java/baseball/GameManager.java
> +            throw new NullPointerException();
컨벤션을 지켜주세요 🙂

[중괄호](https://naver.github.io/hackday-conventions-java/#braces-knr-style)
[공백 삽입](https://naver.github.io/hackday-conventions-java/#space-around-brace)

```suggestion
        if (scanner == null) {
            throw new NullPointerException();
        }
```

2021-02-21 13:53 UTC, kouz95 commented on src/main/java/baseball/GameManager.java
> +        if(scanner == null)
개인적으로 파라미터에 대한 null 처리는 안하는 편입니다.
만약, 라이브러리를 개발하고 있는 것이라면 파라미터로 null이 들어왔을때 빨리 탈출 시키는게 안전하다는 생각을 하겠지만, 지금과 같은 경우는 그렇게 큰 문제가 생길것 같진 않아보여서요! (정답이라고 생각하기보단 취향인 것 같기도해요)

그리고 만약 null처리를 하고 싶다면 `Objects.requireNonNull` api를 사용해서 처리할것 같아요.

```java
if (scanner == null) {
    throw new NullPointerException();
}
```
와 `Objects.requireNonNull(scanner);`는 같은 동작을 합니다 🙂

2021-02-21 13:53 UTC, kouz95 commented on src/main/java/baseball/GameManager.java
> +        boolean continueGame = true;
```suggestion
        boolean continueGame;
```
으로 해도 문제 없겠네요.

2021-02-21 13:53 UTC, kouz95 commented on src/main/java/baseball/GameManager.java
> +        while(continueGame) {
컨벤션!

2021-02-21 13:53 UTC, kouz95 commented on src/main/java/baseball/GameManager.java
> +        while(!result.isThreeStrike()) {
컨벤션! 
자동 줄 정렬 기능 (Reformat code) 를 활용하면 IDE가 한방에 정렬 해줍니다 🙂

2021-02-21 13:53 UTC, kouz95 commented on src/main/java/baseball/GameManager.java
> +            boolean isValidInput = false;
```suggestion
            boolean isValidInput;
```
로 해도 상관 없겠군요

2021-02-21 13:53 UTC, kouz95 commented on src/main/java/baseball/GameManager.java
> +            if(!isValidInput) continue;
```suggestion
            if (!isValidInput) {
                continue;
            }
```
한 줄이어도 중괄호를 열어주도록 해요 🙂

2021-02-21 13:53 UTC, kouz95 commented on src/main/java/baseball/generator/RandomNumberGenerator.java
> +    public static void generate(GameNumber seedNumber) {
`Generator`가 의도한대로 동작하고 있나요?

generate 메소드는 현재 void이고 주입된 seedNumber의 상태를 변경시키는 동작을 하고 있습니다. 

1. generate의 return type은 `GameNumber`가 더 적절하지 않을까요?

2. `GameNumber`가 외부 객체로 인해 상태가 변경되고 있습니다. 괜찮을까요?

---

2번에 관련된 내용은 _객체의 자율성_ 이 키워드 입니다.

> 객체는 자율적인 존재이다. 객체지향의 세계에서 객체는 다른 객체의 상태에 직접적으로 접근할 수도, 상태를 변경할 수도 없다. 자율적인 객체는 스스로 자신의 상태를 책임져야 한다.
>
> _객체지향의 사실과 오해 - 조영호_

객체지향에 대한 이해를 쌓아가면서 천천히 고민해봐도 좋습니다 🙂
객체지향의 사실과 오해는 좋은 책이니 추천드립니다.

2021-02-21 13:53 UTC, kouz95 commented on src/main/java/baseball/number/GameNumber.java
> +    }
seedNumber와 userNumber를 빈값으로 미리 초기화해 두기 위해 사용되고 있는것 같아요.
객체를 미리 생성시키고 setter를 이용하여 값을 조정하는 것이 아니라, 객체가 생성될때 적절한 값과 함께 생성시킨다면 `public GameNumeber(String number)` 생성자만 존재해도 충분히 동작할 수 있지 않을까요?

---

제가 느끼기엔 아무런 파라미터를 받지 않는 기본생성자를 보면 어떠한 필드도 초기화 시키지 않을 것 같다는 생각이 듭니다. (null 상태) 만약 빈 value를 갖고 생성되기를 원한다면 `new GameNumber("")` 로 사용할 것 같아요.

하지만 만약 빈 value를 갖고 생성되는 유즈케이스가 많아진다면 매번 넣어주는게 귀찮을수도 있죠. 이런 경우엔 [정적 팩토리 메서드](https://woowacourse.github.io/javable/post/2020-05-26-static-factory-method/)를 사용하여 `GameNumber.empty()` 라는 메소드를 만들어 줄 것 같아요.

2021-02-21 13:53 UTC, kouz95 commented on src/main/java/baseball/number/GameNumber.java
> +    public void compare(GameNumber userNumber, Result result) {
메소드 길이가 길땐 이 메소드가 한 가지 기능을 하고 있나 생각해볼 수 있습니다.
[하나의 메서드는 하나의 기능을 수행하자](https://woowacourse.github.io/javable/post/2020-05-10-single-job-method/)

가독성을 고려하면서 리팩토링 해보도록해요 🙂
숫자야구 게임만 아는 사람이 이 코드를 보고도 이해할 수 있을까요?

2021-02-21 13:53 UTC, kouz95 commented on src/main/java/baseball/receiver/ConsoleInputReceiver.java
> +
```suggestion
public class ConsoleInputReceiver implements InputReceiver {
    private static final int START_GAME = 1;

    private final Scanner scanner;
```

상수는 클래스 최상위에 private static final을 사용합니다 🙂

2021-02-21 13:53 UTC, kouz95 commented on src/main/java/baseball/receiver/ConsoleInputReceiver.java
> +    }
`ConsoleInputReceiver`의 책임은 사용자의 입력을 받는것으로 끝내도 되지 않을까요?
[단일 책임 원칙](https://woowacourse.github.io/javable/post/2020-07-31-solid-1/)

1 또는 2가 재시작, 종료라는 것은 숫자 야구 게임이라는 세상의 규칙, 비지니스 로직 이라고 생각이 됩니다.
input과 output에 관한 로직을 합쳐 view 로직이라고도 말하는데, 뷰 로직과 비지니스 로직을 분리해보도록 해요.

2021-02-21 13:53 UTC, kouz95 commented on src/test/java/baseball/number/GameNumberTest.java
> +        GameNumber[] userNumbers = new GameNumber[TEST_CASE_NUM];
배열보단 List를 사용해보도록 해요. Java의 Collection API엔 활용 가능한 메소드들이 많습니다.

2021-02-22 00:57 UTC, pkalsh commented on src/main/java/baseball/generator/RandomNumberGenerator.java
> +    public static void generate(GameNumber seedNumber) {
다시 보니 난수를 생성하고 시드번호에 값을 수정하는 일까지 하고 있네요.
수정하는 작업 단위도 하나의 책임이 될 수 있다는 것을 배웁니다. 😄 
책 추천해주신거 바로 주문했어요.
책 읽는거 좋아하니 많이 추천해주시면 좋겠습니다~

2021-02-22 01:53 UTC, kouz95 commented on src/main/java/baseball/generator/RandomNumberGenerator.java
> +    public static void generate(GameNumber seedNumber) {
- 클린코드 - 로버트 C. 마틴
- 이펙티브 자바 - 조슈아 블로크

추천드립니다. 🙂

두 책 모두 지금 봤을때 도움될 만한 내용과, 문제를 마주치기 전까진 이해하기 힘든 내용이 같이 있는 책이라고 생각됩니다. 특히 이펙티브 자바는 정주행하여 독파하겠다는 생각보단 이해가 되는 부분을 위주로 가볍게 읽고, 미션을 하면서 고민되는 부분이 생겼을때 관련된 내용 찾아 읽었을때 도움이 많이 되었던 책입니다.

2021-02-22 02:08 UTC, pkalsh commented on src/main/java/baseball/generator/RandomNumberGenerator.java
> +    public static void generate(GameNumber seedNumber) {
다 주문했습니다~ 미션하면서 읽어보고 생각을 많이 해봐야겠네요.
감사합니다 👍 👍

2021-02-22 02:12 UTC, kouz95 commented on src/main/java/baseball/generator/RandomNumberGenerator.java
> +    public static void generate(GameNumber seedNumber) {
읽으면서 도움이 되었던 내용들은 같은 팀원이나 슬랙에 공유해주시면 좋을 것 같아요 🙂
(모두가 책을 사게 만들어보세요 ㅋㅋ)

2021-02-22 02:21 UTC, pkalsh commented on src/main/java/baseball/generator/RandomNumberGenerator.java
> +    public static void generate(GameNumber seedNumber) {
ㅋㅋㅋ 도움된 내용들은 매일 공유하면서 정리하는 것도 괜찮겠네요
책 전파는 @jjanggyu 부터 시작해보겠습니다

2021-02-22 04:58 UTC, pkalsh commented on src/main/java/baseball/Application.java
> +        } catch (NullPointerException e) {
참조형 변수를 파라미터로 받아서 쓸때마다 안전성을 고려해 명시적으로 널체킹을 해줘 봤는데 리뷰를 확인하고 보니
catch 문에서 딱히 하는일이 없고 오히려 디버깅을 힘들게 하는것 같네요.
지식이 늘었습니다

2021-02-22 05:32 UTC, pkalsh commented on src/main/java/baseball/GameManager.java
> +        while(!result.isThreeStrike()) {
8.1. 공백으로 줄을 끝내지 않음
이 컨벤션에 해당하는 건가요?
그러면 이 컨벤션에서는 가독성을 위한 공백은 허용하지 않는것인가요?
아니면 코드 블럭의 의미 구분을 위한 공백은 허용하나요?

2021-02-22 05:40 UTC, kouz95 commented on src/main/java/baseball/GameManager.java
> +        while(!result.isThreeStrike()) {
```suggestion
        while (!result.isThreeStrike()) {
```
을 의미 했었습니다!

8.1의 no-trailing-spaces 는 빈 줄에 공백을 넣는 행위를 의미하는것으로 보여지네요!
```
 
```
```
	
```
(보일진 모르겠지만 1 space와 1 tab이 들어있습니다.)

가독성을 위한 공백, 의미 구분을 위한 공백 전부 허용됩니다.
불필요한 공백만 아니면 됩니다 🙂

클린코드에 나오는 내용인데 관련하여 정리된 블로그글이 있어 공유드립니다.

[Clean Code -형식 맞추기-](https://medium.com/@ish453525/clean-code-%ED%98%95%EC%8B%9D-%EB%A7%9E%EC%B6%94%EA%B8%B0-b6ee86a45e99)

블로그글엔 소개되지 않았지만, 책에 나와있는 _내려가기 규칙_ 도 개인적으로 감명 깊게 봤던 부분이니 책이 도착하면 읽어보시기 바랍니다 🙂

2021-02-22 17:09 UTC, closed without merging